authors = ["aram@stackpop.com"]
description = ""
language = "rust"
manifest_version = 3
name = "mocktioneer-adapter-fastly"
service_id = ""

[local_server]

[scripts]
  build = "cargo build --profile release --target wasm32-wasip1"
