# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["aram@stackpop.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "mocktioneer"
service_id = ""

[local_server]

[scripts]
  build = "cargo build --profile release --target wasm32-wasip1"